# workaround for https://github.com/jitpack/jitpack.io/issues/1887

jdk:
  - oraclejdk8
before_install:
   - wget http://central.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.6/sbt-launch-1.2.6.jar
install:
   - java -jar sbt-launch-1.2.6.jar publishM2
