language: scala
sudo: false

scala:
- 2.11.12
- 2.12.8
- 2.13.0

jdk:
- oraclejdk8
- oraclejdk11

script:
- sbt ++$TRAVIS_SCALA_VERSION test
- sbt ++$TRAVIS_SCALA_VERSION bench/compile

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
before_cache:
  # Tricks to avoid unnecessary cache updates
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

